Repository iver-wharf/wharf-web, pull requests merged in 2021-09, with the labels that each got.

#60 Fixed build logs page scroll
  CHANGELOG.md
  src/app/builds/build-details/build-details.component.ts
Labels: bug

#59 Added dynamic & descriptive titles
  CHANGELOG.md
  README.md
  src/app/app.module.ts
  src/app/builds/build-details/build-details.component.html
  src/app/builds/build-details/build-details.component.ts
  src/app/projects/project-details/project-details.component.html
  src/app/projects/project-details/project-details.component.ts
  src/app/projects/project-list/project-list.component.html
  src/app/projects/project-list/project-list.component.ts
  src/index.html
Labels: enhancement

#58 Added favoriting project from project details view functionality
  CHANGELOG.md
  src/app/projects/project-details/project-details.component.html
  src/app/projects/project-favorite/project-favorite-button.component.html
  src/app/projects/project-favorite/project-favorite-button.component.ts
  src/app/projects/project-list/project-list-item.component.html
  src/app/projects/project-list/project-list-item.component.ts
  src/app/projects/projects.module.ts
  src/scss/imports.scss
  src/scss/project-favorite-button.component.scss
Labels: enhancement

#54 Added toast for ProblemResponse errors
  CHANGELOG.md
  src/app/providers/provider-form/azuredevops/azuredevops.component.ts
  src/app/providers/provider-form/github/github.component.ts
  src/app/providers/provider-form/gitlab/gitlab.component.ts
  src/app/shared/error/global-error-handler.ts
  src/app/shared/notification/notification.component.html
  src/app/shared/notification/notification.component.ts
  src/app/shared/notification/notification.service.ts
  src/scss/base/reset/p-toast.scss
Labels: enhancement

#65 Use ng build -c production instead of --prod
  package.json
Labels: enhancement

#66 Fixed various docker vulnerabilities
  CHANGELOG.md
  Dockerfile
Labels: bug

#64 Release v1.4.0
  CHANGELOG.md
Labels: release

#69 Removed per-tab title for build & project details pages
  CHANGELOG.md
  src/app/builds/build-details/build-details.component.html
  src/app/builds/build-details/build-details.component.ts
  src/app/projects/project-details/project-details.component.html
  src/app/projects/project-details/project-details.component.ts
Labels: enhancement

#68 Fix changelog note for #66
  CHANGELOG.md
Labels: documentation

#67 Added Makefile & updated Dockerfile with labels
  CHANGELOG.md
  Dockerfile
  Makefile
  README.md
  deploy/update-typescript-environments.sh
Labels: enhancement
