Repository iver-wharf/wharf-web, pull requests merged in 2021-06, with the labels that each got.

#8 Bind provider form to api call
  CHANGELOG.md
  src/app/providers/provider-form/github/github-form.model.ts
  src/app/providers/provider-form/github/github.component.html
  src/app/providers/provider-form/github/github.component.ts
  src/app/providers/providers.module.ts
  src/app/providers/providers.service.ts
  src/app/shared/config/config.service.ts
Labels: enhancement

#26 Added stylelint
  .stylelintrc.json
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  src/app/app.component.scss
  src/app/shared/tabview-x/tabview-x.component.scss
  src/scss/actions-modal.component.scss
  src/scss/artifacts-list.component.scss
  src/scss/base/reset.scss
  src/scss/base/reset/p-button.scss
  src/scss/base/reset/p-dialog.scss
  src/scss/base/reset/p-dropdown.scss
  src/scss/base/reset/p-splitbutton.scss
  src/scss/base/reset/p-tabview.scss
  src/scss/base/reset/p-toast.scss
  src/scss/base/typography.scss
  src/scss/build-details.component.scss
  src/scss/code-blocks.scss
  src/scss/imports.scss
  src/scss/links.scss
  src/scss/nav.component.scss
  src/scss/project-details.component.scss
  src/scss/project-list-item.component.scss
  src/scss/project-list.component.scss
  src/scss/provider.component.scss
  src/scss/variables.scss
Labels: documentation, enhancement

#24 Version of remote components
  CHANGELOG.md
  projects/projects.module.ts
  src/app/app.module.ts
  src/app/nav/nav.component.html
  src/app/nav/nav.component.ts
  src/app/nav/nav.module.ts
  src/app/providers/providers.module.ts
  src/scss/base/reset.scss
  src/scss/nav.component.scss
  src/scss/variables.scss
Labels: enhancement

#29 Restyled logs
  CHANGELOG.md
  src/app/builds/build-details/build-details.component.html
  src/app/builds/build-details/build-details.component.ts
  src/scss/build-details.component.scss
  src/scss/variables.scss
Labels: enhancement

#27 Angular 12
  .browserslistrc
  CHANGELOG.md
  Dockerfile
  README.md
  angular.json
  e2e/tsconfig.json
  package-lock.json
  package.json
  projects/api-client/package.json
  projects/api-client/tsconfig.lib.json
  projects/api-client/tsconfig.lib.prod.json
  projects/import-azuredevops-client/package.json
  projects/import-azuredevops-client/tsconfig.lib.json
  projects/import-azuredevops-client/tsconfig.lib.prod.json
  projects/import-github-client/package.json
  projects/import-github-client/tsconfig.lib.json
  projects/import-github-client/tsconfig.lib.prod.json
  projects/import-gitlab-client/package.json
  projects/import-gitlab-client/tsconfig.lib.json
  projects/import-gitlab-client/tsconfig.lib.prod.json
  src/app/projects/project-details/project-details-build/project-details-build.component.html
  src/app/projects/project-refresh/project-refresh-base.component.ts
  src/app/shared/local-storage/local-storage.service.ts
  src/app/shared/tabview-x/tabview-x.component.ts
  src/app/shared/tabview-x/tabview-x.module.ts
  src/environments/environment.ts
  src/polyfills.ts
  src/test.ts
  tsconfig.json
Labels: enhancement

#28 PrimeNG 12
  CHANGELOG.md
  package-lock.json
  package.json
  src/scss/nav.component.scss
  src/scss/project-details.component.scss
  src/scss/project-list-item.component.scss
Labels: enhancement

#23 Fix all missing dangling commas
  .eslintrc.json
  src/app/animations/wharf-spinner-animation/wharf-spinner-animation.component.ts
  src/app/app-routing.module.ts
  src/app/app-utils.service.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/artifacts/artifacts-list/artifacts-list.component.ts
  src/app/artifacts/artifacts.module.ts
  src/app/builds/build-details/build-details.component.ts
  src/app/builds/builds.module.ts
  src/app/nav/nav.component.ts
  src/app/nav/nav.module.ts
  src/app/projects/actions-modal/actions-modal.component.ts
  src/app/projects/actions-modal/actions-modal.service.ts
  src/app/projects/project-details/project-details-build/project-details-build.component.ts
  src/app/projects/project-list/project-list-item.component.ts
  src/app/projects/project-list/project-list.component.ts
  src/app/projects/project-refresh/project-refresh-base.component.ts
  src/app/projects/project-utils.service.ts
  src/app/projects/projects.module.ts
  src/app/providers/provider-form/azuredevops/azuredevops.component.ts
  src/app/providers/provider-form/gitlab/gitlab.component.ts
  src/app/providers/provider-form/provider-form.component.ts
  src/app/providers/provider/provider.component.ts
  src/app/providers/providers.module.ts
  src/app/providers/providers.service.ts
  src/app/shared/config/config.service.provider.ts
  src/app/shared/config/config.service.ts
  src/app/shared/error/error.service.ts
  src/app/shared/error/global-error-handler.ts
  src/app/shared/notification/notification.module.ts
  src/app/shared/notification/notification.service.ts
  src/app/shared/pipes/date.pipe.ts
  src/app/shared/pipes/isvalid.pipe.ts
  src/app/shared/pipes/shared.module.ts
  src/app/shared/tabview-x/tabview-x.component.ts
  src/app/shared/tabview-x/tabview-x.module.ts
  src/test.ts
Labels: enhancement

#32 Added back @angular-devkit/architect
  CHANGELOG.md
  package-lock.json
  package.json
Labels: bug

#31 Release v1.3.0
  CHANGELOG.md
Labels: enhancement

#34 Regenerated projects
  CHANGELOG.md
  packages-microsoft-prod.deb
  projects/api-client/src/api/artifact.service.ts
  projects/api-client/src/api/branch.service.ts
  projects/api-client/src/api/branches.service.ts
  projects/api-client/src/api/build.service.ts
  projects/api-client/src/api/health.service.ts
  projects/api-client/src/api/logs.service.ts
  projects/api-client/src/api/meta.service.ts
  projects/api-client/src/api/project.service.ts
  projects/api-client/src/api/provider.service.ts
  projects/api-client/src/api/token.service.ts
  projects/api-client/src/model/appVersion.ts
  projects/api-client/src/model/mainArtifact.ts
  projects/api-client/src/model/mainBranch.ts
  projects/api-client/src/model/mainBuild.ts
  projects/api-client/src/model/mainBuildLog.ts
  projects/api-client/src/model/mainBuildParam.ts
  projects/api-client/src/model/mainBuildReferenceWrapper.ts
  projects/api-client/src/model/mainHealthStatus.ts
  projects/api-client/src/model/mainLog.ts
  projects/api-client/src/model/mainPaginatedBuilds.ts
  projects/api-client/src/model/mainPing.ts
  projects/api-client/src/model/mainProject.ts
  projects/api-client/src/model/mainProvider.ts
  projects/api-client/src/model/mainTestsResults.ts
  projects/api-client/src/model/mainToken.ts
  projects/api-client/src/model/mainTokenWithProviderID.ts
  projects/api-client/src/model/nullString.ts
  projects/api-client/src/model/problemResponse.ts
  projects/import-azuredevops-client/src/api/default.service.ts
  projects/import-azuredevops-client/src/api/meta.service.ts
  projects/import-azuredevops-client/src/model/appVersion.ts
  projects/import-azuredevops-client/src/model/mainAzureDevOpsPR.ts
  projects/import-azuredevops-client/src/model/mainAzureDevOpsPRResource.ts
  projects/import-azuredevops-client/src/model/mainAzureDevOpsPr.ts
  projects/import-azuredevops-client/src/model/mainAzureDevOpsPrResource.ts
  projects/import-azuredevops-client/src/model/mainImport.ts
  projects/import-azuredevops-client/src/model/mainImportBody.ts
  projects/import-azuredevops-client/src/model/wharfapiProjectRunResponse.ts
  projects/import-github-client/src/api/default.service.ts
  projects/import-github-client/src/api/meta.service.ts
  projects/import-github-client/src/model/appVersion.ts
  projects/import-github-client/src/model/mainImport.ts
  projects/import-github-client/src/model/mainImportBody.ts
  projects/import-gitlab-client/src/api/default.service.ts
  projects/import-gitlab-client/src/api/meta.service.ts
  projects/import-gitlab-client/src/model/appVersion.ts
  projects/import-gitlab-client/src/model/mainImport.ts
Labels: enhancement

#35 Fixed provider API's getting main API's config
  CHANGELOG.md
  projects/projects.module.ts
Labels: bug

#6 Defend from error on invalid URL
  CHANGELOG.md
  src/app/projects/project-list/project-list-item.component.ts
  src/app/providers/provider-form/azuredevops/azuredevops-form.model.ts
  src/app/providers/provider-form/azuredevops/azuredevops.component.html
  src/app/providers/provider-form/azuredevops/azuredevops.component.ts
  src/app/providers/provider-form/github/github-form.model.ts
  src/app/providers/provider-form/github/github.component.html
  src/app/providers/provider-form/github/github.component.ts
  src/app/providers/provider-form/gitlab/gitlab-form.model.ts
  src/app/providers/provider-form/gitlab/gitlab.component.html
  src/app/providers/provider-form/gitlab/gitlab.component.ts
  src/app/providers/providers.module.ts
Labels: enhancement

#4 Add book icon with docs link to title header
  CHANGELOG.md
  src/app/nav/nav.component.html
  src/app/nav/nav.component.ts
Labels: enhancement

#39 Add missing validator file
  CHANGELOG.md
  src/app/shared/validator-functions/invalid-url-validator.directive.ts
Labels: bug

#42 Updated to primeng@12.0.0 (no -rc)
  CHANGELOG.md
  package-lock.json
  package.json
Labels: enhancement

#41 Removed packages-microsoft-prod.deb
  packages-microsoft-prod.deb
Labels: bug
